# Usar a imagem oficial do Node.js
FROM node:22

# Instalar dependências do sistema, incluindo o PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json para dentro do container
COPY ./package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o código do backend para dentro do container
COPY ./src ./src

# Copiar o arquivo tsconfig.json para o contêiner
COPY ./tsconfig.json ./tsconfig.json

# Gerar o cliente Prisma
RUN npx prisma generate --schema=/app/src/app/prisma/schema.prisma

# Compilar o código TypeScript (se necessário)
RUN npm run build

# Expor a porta que o backend vai rodar
EXPOSE 8080

# Definir o comando para rodar a aplicação
CMD ["npm", "run", "start"]
