# Usar a imagem oficial do Node.js para React
FROM node:22

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY ./package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o código fonte do frontend para dentro do container
COPY ./src ./src

# Expor a porta onde o React vai rodar
EXPOSE 80

# Comando para rodar o frontend (React)
CMD ["npm", "run", "dev"]
